---
permalink: /:year/:month/:day/:title.html
maruku:
  png_dir: images/latex
  png_url: /images/latex
  use_tex: false
  use_divs: false
lsi: false
destination: ./_site
markdown: maruku
exclude:
- config
- CNAME
- Rakefile
- Capfile
- _site.tar.gz
pygments: true
pretty_style: html_extension
auto: true
server_port: 4000
